### ISSUE TITLE
[BUG] Asynchronous Chunk get entities call (Airplane 1.8.8)

### ISSUE THREAD

**Issue by 1CAMOU** [PluginBugs/Issues-ServerBooster#34]
**Describe the bug**
I am getting a console error for Asynchronous Chunk getting entties called!

**To Reproduce**
1. Join 1.16.4 ViaVersion server with version 1.8

**Expected behavior**
no errors.

**Info (please complete the following information):**
 - Server version: Airplane 1.16.4
 - Client version: 1.8.8
 - Plugin version: latest

**Comment by LoneDev6** [comment]
Can you try on normal Spigot / Paper?
I think that issue is from unofficial frorks.

Let me know
