### ISSUE TITLE
[Suggestion] Force on all Worlds

### ISSUE THREAD

**Issue by JamesBach93** [PluginBugs/Issues-ServerBooster#36]
**Is your feature request related to a problem? Please describe.**
On my Server Users can have own Worlds. I don't want everytime edit the Config manuell.
So an way to force all Worlds.

**Describe the solution you'd like**
All Worlds are automaticly in the whitelist. 

**Describe alternatives you've considered**
An way to change the Worlds Whitelist to Worlds Blacklist.
That the Worlds in the List dont check.

**Additional context**

**Comment by LoneDev6** [comment]
Thanks for the suggestion and sorry for the delay, I implemented that in the new update.
Just add ALL in each .yml file, under the worlds setting.

```yml
  worlds:
  - ALL
```
