### ISSUE TITLE
[Suggestion] Inventory Stacking

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ServerBooster#37]
Ability to have items like buckets and potions stack to 64 in Inventory, only reason i'm using a limited free alternative. If it could do this i'd definitely purchase it.

There was an issue of item duping in this free inventory stacking plugin, where if you swiftly moved items between epicbackpacks backpack and vanilla inventory, items would multiply They've fixed it so this would be very much possible to implement.

I'd welcome the addition of serverbooster to my server if it could do the same.

**Comment by LoneDev6** [comment]
Hello, this plugin doesn't aim to modify the vanilla inventory (note: this task is likely to cause dupe bugs because of how the game is coded), this plugin aims to optimize the server, in this case avoid too many dropped items on the ground.
