### ISSUE TITLE
[BUG] Location is from different world! ERROR

### ISSUE THREAD

**Issue by arturek1666** [PluginBugs/Issues-ServerBooster#38]
**Describe the bug**
Not 100% sure but this error has to do something with a world change or world management. It happens quite often 
The error:
https://gist.github.com/arturek1666/7e8f8fe017b1d817681b16f861f681e0

It looks like bukkit/paper/java has something to do with the error
**To Reproduce**
To reproduce try to have multiversecore or managing world plugin and try to go to different worlds, and it should show up.

**Expected behavior**
Everytime player moves from one world to another that error shows up. While it should show no error.

**Info:**
 - Server version: 1.16.4 SSspigot
 - Client version: 1.16.4
 - Plugin version: 1.0.50

**Comment by LoneDev6** [comment]
Thanks, I may have fixed that but since I cannot reproduce the problem it's hard to tell.
Let me know in the next update.
