### ISSUE TITLE
[BUG] forceoptimize cause an error

### ISSUE THREAD

**Issue by LRoffic** [PluginBugs/Issues-ServerBooster#39]
**Describe the bug**
Hello, when i use /serverbooster mobs forceoptimize i have this error: https://pastebin.com/U1rypiAa

**To Reproduce**
1. Install the plugin
2. start and go on the server
3. Use the command /serverbooster mobs forceoptimize
4. See error in console

**Expected behavior**
Correct the bug please ^^"

**Info (please complete the following information):**
 - Server version: Yatopia 1.16.4 build 3770a43
 - Client version: 1.16.4
 - Plugin version: 1.0.50

**Comment by LoneDev6** [comment]
Thanks! Sorry for the delay, I fixed the issue and I will post an update today
