### ISSUE TITLE
Lastest ServerBooster version may be crashing Paper [BUG] 

### ISSUE THREAD

**Issue by plebexer** [PluginBugs/Issues-ServerBooster#40]
**Describe the bug**
on the lastest Serverbooster version with an amount of aproximately 30 players the server can crash, because of the getchunk value as i can see

**Expected behavior**
the server will stop suddenly and you will get errors with chunks in the console

**Info (please complete the following information):**
 - Server version: Paper Legacy 1.15.2
 - Plugin version: 1.0.51

**Additional context**
I will send you the logs when this happened:

[latest.log](https://github.com/PluginBugs/Issues-ServerBooster/files/5896118/latest.log)

from what i can see there is a line that says the following in the crash dump:
[16:32:36] [Paper Watchdog Thread/ERROR]: 		org.bukkit.Location.getChunk(Location.java:123)
[16:32:36] [Paper Watchdog Thread/ERROR]: 		dev.lone.serverbooster.e.c.j(SourceFile:29)

and as i did search the problem i found something related to it and plugins trying to get chunk locations crashing the server with paper, and that is because it seems that you have to use the paper api or something, but that is just what i found, i dont know much about programming so i will let you do the research.

**Comment by LoneDev6** [comment]
Thanks for the report, this should be fixed in the upcoming update, sorry for the delay
