### ISSUE TITLE
[Suggestion] automatic commands

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ServerBooster#41]
Matteo, ciao, come va? puoi aggiungere una nuova funzione a ServerBooster per favore?
Visto che questo plugin è in grado di fare il check dei tps del server... potresti aggiungere un nuovo file yml nella quale è possibile aggiungere dei comandi custom che vengono eseguiti quando i tps raggiungono un determinato valore?
un file con qualcosa tipo cosi

CheckIntervalTick: 6000 
TPS: 15
DelayInSeconds: 2 (delay beetween commands, set 0 for let them execute instantly togheter)
Commandtoexecute:
- say hello
- say hello2

**Comment by LoneDev6** [comment]
verrà aggiunto nel prossimo update

**Comment by Fargus5** [comment]
grazie caro
