### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Westloch** [PluginBugs/Issues-ServerBooster#42]
**Describe the bug**
No matter what the limit for zombified piglins is set to, it seems like ServerBooster does not take into account the zombified piglins that come through a nether portal into the overworld. The limits i set for the zombified piglins are:

```
  zombified_piglin:
    radius_max: 5
    chunk_max: 2
    cull: 2
```

And still a player can stack hundreds of zombified piglins in a single chunk/radius

**To Reproduce**
1. Set zombified piglin limit to something low (in config.yml)
2. Create this style of farm https://youtu.be/xDCO7ZiaoLY , just nether portals with  snow golems to attract piglins to center
3. Load the chunk, and afk
4. Watch the zombified piglins stack indefinetly

**Expected behavior**
Have any mob coming through portals respect the limits set

**Info (please complete the following information):**
 - Paper 1.16.2
 - Plugin version: ServerBooster v1.0.51
 
 

https://user-images.githubusercontent.com/62856212/107886453-93aaf780-6ec5-11eb-9f73-10326d52bee0.mp4

**Comment by Westloch** [comment]
i have been doing lots of testing and came across this feature in the config:

`force-spawn-deny: true/false`

i had it set to `false`, and i had the issue with the piglins spawning non stop no matter the limit set (issue mentioned above.

since then i set the option to `true` and now only the piglins i have set spawn. in my case 5 per radius


im not to sure what  `force-spawn-deny: true/false` does, but it seems to have fixed this issue?

**Comment by LoneDev6** [comment]
Thanks this should be fixed in the upcoming update
