### ISSUE TITLE
[BUG] item

### ISSUE THREAD

**Issue by LivingDarkness** [PluginBugs/Issues-ServerBooster#44]
Ho riscontrato problemi con il blocco "Stripped warped stem" che quando lanciato a terra il colore della sua scrittura è grigio anziché bianco e non e non viene tradotto in altre lingue, e la "bedrock" che quando viene droppata a terra non dal l'ologramma con il nome dell'oggetto e la quantità, ma se droppi un secondo blocco di bedrock darà l'ologramma ma dirà che c'è solo un oggetto ma invece ce ne sono due, ti lascio un video qui: https://youtu.be/1DlODoSlGp8
versione del server: 1.16.5
versione del plugin: 1.0.54

**Comment by LoneDev6** [comment]
Il bug del "Stripped warped stem"  non riesco a riprodurlo.
![immagine](https://user-images.githubusercontent.com/27242001/146190806-279f5eb6-b2d6-41d3-a2d7-d4b8e0cdec67.png)
I file linguaggio li trovi qui: http://matteodev.it/spigot/holodrops/assets/lang.zip

Il bug del materiale bedrock non è un bug ed è dovuto al fatto che è impostato nella blacklist del plugin nel file config_holo.yml
```yml
  blacklist:
  - BEDROCK
```
