### ISSUE TITLE
[BUG] Error occurred while enabling ServerBooster v1.0.55 (Is it up to date?) java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by taka1945** [PluginBugs/Issues-ServerBooster#45]
**Describe the bug**
https://pastebin.com/WuLY8kEj

**Info (please complete the following information):**
 - Server version: CraftBukkit version 3164-Spigot-f773da8-b069f22 (MC: 1.17) 
 - Plugin version: ServerBooster-1.0.55

**Comment by LoneDev6** [comment]
Send the complete log

**Comment by taka1945** [comment]
I think problems is config_holo.yml ,  about language  en_us set to zh_tw ,
than it just show that error message.

tried  spigot 1.17 , paper 1.17 , purpur 1.17

complete log (zh_tw) 
https://pastebin.com/B7B0c9h5

complete log (en_us)
https://pastebin.com/cMKdJ6qg

**Comment by LoneDev6** [comment]
Download the missing language file
https://serverbooster.devs.beer/configurations/language

Let me know

**Comment by LoneDev6** [comment]
[zh_tw.zip](https://github.com/PluginBugs/Issues-ServerBooster/files/6748371/zh_tw.zip)

**Comment by LoneDev6** [comment]
Thanks for the report, an update will be published today

**Comment by LoneDev6** [comment]
[download here](https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1.72184/)
