### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Bronzwar** [PluginBugs/Issues-ServerBooster#50]
**Describe the bug**
https://paste.helpch.at/ixegovopil.md

**Expected behavior**
My players just mining 

**Info (please complete the following information):**
 - Server version: 1.17.1.
 - Client version: Forge 1.17.1.
 - Plugin version: 1.0.57

**Additional context**
https://paste.helpch.at/esiyeqicox.md

**Comment by LoneDev6** [comment]
Thanks, I found the issue, it's a bug of EpicBackpacks, I'll fix it in the next days

**Comment by LoneDev6** [comment]
Please download the new EpicBackpacks version 1.3.12
