### ISSUE TITLE
Could not pass event InventoryPickupItemEvent to ServerBooster v1.0.57 [BUG] 

### ISSUE THREAD

**Issue by Soapx91** [PluginBugs/Issues-ServerBooster#51]
**Describe the bug**
Could not pass event InventoryPickupItemEvent to ServerBooster v1.0.57

**To Reproduce**
I believe it happens when either mobs or entities are stacked?

**Expected behavior**
Not have an error

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://pastebin.com/1cqNqnev)

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**

**Comment by LoneDev6** [comment]
I can't access the error log, please paste it here
