### ISSUE TITLE
[BUG] Speed of mobs

### ISSUE THREAD

**Issue by Keliop** [PluginBugs/Issues-ServerBooster#53]
When I installed the plugin, all the mobs started to move at the speed of light, I tried removing the plugin and the problem was solved, also the mobs don't stack and it seems that their spawn is also bugged. I tried this plugin on another test server (I own all the servers) and the same thing happened, I didn't find any solution.

https://user-images.githubusercontent.com/98917146/152233313-3e506510-9f70-45b0-aa4c-45eb6a30c021.mp4

**Comment by LoneDev6** [comment]
### Movement speed bug

This problem should have been fixed in previous updated, what is your server version?

### Stack

This plugin doesn't stack mobs because it's useless, it optimizes all mobs so there is no need to stack them
