### ISSUE TITLE
[BUG] ServerBooster Console Spam with [INFO] Messages

### ISSUE THREAD

**Issue by CitizenPrayer** [PluginBugs/Issues-ServerBooster#63]
Good Morning. I am running a Spigot server at 1.19.2 and running the most up to date Server Booster version. I also have several worlds on MultiVerse.

I can't seem to find a setting somewhere in the configs, and setting "log" to false on literally everything, still produces a plethora of console "INFO" messages. While I appreciate the information, and do want it logged, I don't want it to show in the console.

The vast majority of my Multiverse worlds aren't loaded when no-one is actively using them. So the only world that should be loaded when no one is on the server should be the Spawn world, and even then only the Spawn chunk.

Here's a list of the messages I'm receiving. Perhaps there's a setting that exists somewhere that I can resolve this with?

![image](https://user-images.githubusercontent.com/10674301/194566639-39fd4c74-2b81-4e62-9bae-afd6743df297.png)

I am also seeing this error upon starting ServerBooster:

![image](https://user-images.githubusercontent.com/10674301/194566948-3d38bc18-7a74-4c8b-b809-a68f784ab70d.png)

**Comment by LoneDev6** [comment]
config_optimize_entities.yml
`log-detailed: false`
