### ISSUE TITLE
Mobs moving at very high speed

### ISSUE THREAD

**Issue by lKJD** [PluginBugs/Issues-ServerBooster#68]
tps reduces animal behavior errors

I hope it will be fixed soon

https://drive.google.com/file/d/1iM0ORYyGR1OXKA2JSNNs-3ywyZwts-I7/view?usp=sharing
(MP4)

**Info (please complete the following information):**
 - Server version:Paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 1.1.3-r4

My English is not very good

**Comment by lKJD** [comment]
I am using the default configuration

**Comment by LoneDev6** [comment]
Can you share your full server log?

**Comment by lKJD** [comment]
https://drive.google.com/file/d/1cgVNCVotxrK37IuhdZeMdtS8zXVqur3X/view?usp=share_link

**Comment by LoneDev6** [comment]
Thanks a lot for the patience.
I finally discovered the cause of the issue and I published an update.
