### ISSUE TITLE
Spawner's aniaml have no AI.[BUG] 

### ISSUE THREAD

**Issue by play275** [PluginBugs/Issues-ServerBooster#69]
- Server version: paper1.19.2
 - Client version: 1.19.2
 - Plugin version: 1.1.3-r1

When I unload this plugin,it makes my spawner's aniaml have no AI!How to fix it?

**Comment by LoneDev6** [comment]
By unload what you mean?
You're not supposed to unload the plugin during gameplay.

**Comment by play275** [comment]
Because I delete this plugin after stopping my server,it also happened.

**Comment by LoneDev6** [comment]
You can fix it by doing that:
- open serverbooster config_optimize_entities.yml
- set `disable-tick-for-untracked-entities` and `disable-ai-for-untracked-entities` to false
- start the server with serverbooster
- let it load
- travel around where you can find broken entities
- wait a bit, like 5 minutes
- stop the server
- remove serverbooster

your entities now should have the AI.

If this doesn't work please wait for the new update and redo the same steps I explained before.
