### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cr4ft3rk4n4l** [PluginBugs/Issues-ServerBooster#76]
**Describe the bug**
So i don't know if its a bug but seems like something that normaly shouldnt happen because i have all dependencies and the error is unknown for me

**To Reproduce**
1. Start the Server
2. See error

**Expected behavior**
I wanted that the plugin works

**Screenshots**
Error: https://i.imgur.com/K1XLaCb.png
Plugins: https://i.imgur.com/9hFTrUI.png

**Info:**
 - Server version: (example: paper 1.19.2)
 - Client version: LabyMod4 1.19.2
 - Plugin version: 1.1.5

**Comment by LoneDev6** [comment]
Never post errors as screenshots when you report bugs, not only to me but to any developer.
Anyway update LoneLibs, this error is shown because you didn't update LoneLibs.

Have a nice week!
